const description =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <br/><br/> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
const creator = "Wash Your Hands";
export const ARTWORKS = [
  {
    id: "0",
    title: "Orangey",
    url: "/2.png",
    owner: "aivanBolambao",
    price: "1.22",
    description,
    creator,
  },
  {
    id: "1",
    title: "Pink Ocean",
    url: "/3.png",
    owner: "dbassegio",
    price: "2.93",
    description,
    creator,
  },
  {
    id: "2",
    title: "Neon Halls",
    url: "/4.png",
    owner: "shellyluser",
    price: "1.58",
    description,
    creator,
  },
  {
    id: "3",
    title: "Melancholy",
    url: "/5.png",
    owner: "someRando",
    price: "1.01",
    description,
    creator,
  },
  {
    id: "4",
    title: "Spikey Spikes",
    url: "/6.png",
    owner: "kdgrano",
    price: "1.35",
    description,
    creator,
  },
  {
    id: "5",
    title: "Sploosh",
    url: "/7.png",
    owner: "123abc",
    price: "2.56",
    description,
    creator,
  },
  {
    id: "6",
    title: "asdf",
    url: "/7.png",
    owner: "123abc",
    price: "2.59",
    description,
    creator,
  },
  {
    id: "7",
    title: "Green Art",
    url: "/1.png",
    owner: "SaihajpreetSingh",
    price: "2.75",
    description,
    creator,
  },
  {
    id: "8",
    title: "sdf",
    url: "/2.png",
    owner: "123abc",
    price: "2.10",
    description,
    creator,
  },
];
